resource_types:
  - name: slack_notification
    type: docker-image
    source:
      repository: cfcommunity/slack-notification-resource
      tag: latest

  - name: twitter_notification
    type: docker-image
    source:
      repository: ecsteam/twitter-concourse-resource

resources:
- name: app_sources_dev
  type: git
  source:
    uri: https://github.com/smichard/graphR.git
    branch: dev
    username: {{github_username}}
    password: {{github_password}}
  check_every: 60s

- name: app_sources
  type: git
  source:
    uri: https://github.com/smichard/graphR.git
    branch: master
    username: {{github_username}}
    password: {{github_password}}
  check_every: 60s

- name: version
  type: semver
  source:
    uri: https://github.com/smichard/graphR.git
    branch: version
    username: {{github_username}}
    password: {{github_password}}
    file: version
    driver: git
    initial_version: 0.5.0

- name: docker_hub_dev
  type: docker-image
  source:
    email: {{docker_hub_email}}
    username: {{docker_hub_username}}
    password: {{docker_hub_password}}
    repository: {{docker_hub_dev_repository}}

- name: docker_hub
  type: docker-image
  source:
    email: {{docker_hub_email}}
    username: {{docker_hub_username}}
    password: {{docker_hub_password}}
    repository: {{docker_hub_repository}}

- name: S3_target
  type: s3
  source:
    endpoint: {{s3_endpoint}}
    bucket: releases
    regexp: release_history/graphr_app-(.*)-(.*).tar.gz
    access_key_id: {{s3_key}}
    secret_access_key: {{s3_secret}}

- name: slack_msg
  type: slack_notification
  source:
    url: {{slack_hook}}

- name: twitter_msg
  type: twitter_notification
  source:
    consumer_key: {{twitter_consumer_key}}
    consumer_secret: {{twitter_consumer_secret}}
    access_token: {{twitter_access_token}}
    access_token_secret: {{twitter_access_token_secret}}

jobs:
  - name: build-graphr-app-dev
    public: true
    serial: true
    plan:
    - get: app_sources_dev
      trigger: true
    - put: docker_hub_dev
      params:
        build: app_sources_dev/
        cache: true
        cache_tag: latest
      on_failure:
        do:
        - task: hue_red
          file: app_sources_dev/ci/tasks/hue_red.yml
        - put: slack_msg
          params:
            channel: '#general'
            text: |
              graphR app: The build $BUILD_JOB_NAME with build ID $BUILD_ID for pipeline $BUILD_PIPELINE_NAME failed. Check it out at:
              http://deploy.michard.de/builds/$BUILD_ID
      on_success:
        do:
        - task: hue_green
          file: app_sources_dev/ci/tasks/hue_green.yml
        - put: slack_msg
          params:
            channel: '#general'
            text: |
              graphR app: The build $BUILD_JOB_NAME with build ID $BUILD_ID for pipeline $BUILD_PIPELINE_NAME completed succesfully.

  - name: merge-dev-to-master
    public: true
    plan:
    - get: app_sources_dev
      passed: [ build-graphr-app-dev ]
    - get: version
      trigger: false
    - put: app_sources
      params:
        merge: true
        repository: app_sources_dev
        tag: version/version
      on_failure:
        put: slack_msg
        params:
          channel: '#general'
          text: |
            graphR app: Dev branch failed to merge with master branch. The build $BUILD_JOB_NAME with build ID $BUILD_ID for pipeline $BUILD_PIPELINE_NAME failed. Check it out at:
            http://deploy.michard.de/builds/$BUILD_ID
      on_success:
        put: slack_msg
        params:
          channel: '#general'
          text: |
            graphR app: Dev branch succesfully merged to master branch. The build $BUILD_JOB_NAME with build ID $BUILD_ID for pipeline $BUILD_PIPELINE_NAME completed succesfully.

  - name: build-graphr-app
    public: true
    serial: true
    plan:
    - get: app_sources
      passed: [ merge-dev-to-master ]
      trigger: true
    - put: docker_hub
      params:
        build: app_sources/
        cache: true
        cache_tag: latest
      on_failure:
        do:
        - task: hue_red
          file: app_sources/ci/tasks/hue_red.yml
        - put: slack_msg
          params:
            channel: '#general'
            text: |
              graphR app: The build $BUILD_JOB_NAME with build ID $BUILD_ID for pipeline $BUILD_PIPELINE_NAME failed. Check it out at:
              http://deploy.michard.de/builds/$BUILD_ID
      on_success:
        do:
        - task: hue_green
          file: app_sources/ci/tasks/hue_green.yml
        - put: slack_msg
          params:
            channel: '#general'
            text: |
              graphR app: The build $BUILD_JOB_NAME with build ID $BUILD_ID for pipeline $BUILD_PIPELINE_NAME completed succesfully. New docker container available on docker hub:
              https://hub.docker.com/u/smichard/

  - name: ecs-backup
    public: true
    serial: true
    plan:
    - get: version
    - get: app_sources
      passed: [ build-graphr-app ]
      trigger: true
    - task: create-artifact
      file: app_sources/ci/tasks/create_artifact.yml
    - put: S3_target
      params:
        acl: public-read
        file: ./artifact/graphr_app-*-*.tar.gz
      on_failure:
        put: slack_msg
        params:
          channel: '#general'
          text: |
            graphR app: Artifact could not be uploaded to S3 target. The build $BUILD_JOB_NAME with build ID $BUILD_ID for pipeline $BUILD_PIPELINE_NAME failed. Check it out at:
            http://deploy.michard.de/builds/$BUILD_ID
      on_success:
        put: slack_msg
        params:
          channel: '#general'
          text: |
            graphR app: Artifact succesfully uploaded to S3 target (ECS Testdrive).

  - name: bump-version-minor
    public: true
    plan:
    - aggregate:
      - get: app_sources
        passed: [ ecs-backup ]
        trigger: true
      - get: version
      - put: version
        params:
          bump: minor
      - put: twitter_msg
        params:
          status: >
            Just deployed a new version of the graphR. app with @concourseci (build ${BUILD_ID}) - check it out https://wwww.graphr.de #CI #RVtools
